/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5bc03a82-7d05-43b3-89f1-558ec02cb4bd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ztopBoYoN",
    "aws_user_pools_web_client_id": "3cgrp05k0seagerbfl5h006ot0",
    "oauth": {}
};


export default awsmobile;
